remote_theme: pages-themes/slate@v0.2.0
title: John Aughey's Info
description: github pages hosted content for professional and personal information on John Aughey
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one